// Hand-curated labels that cannot be inferred reliably from font binaries.
export default {
	"Archia": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Argesta Display": [
		"SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Argesta Hairline": [
		"SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Argesta Headline": [
		"SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Bariol": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Bariol Serif": [
		"SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Basier Circle": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Basier Circle Mono": [
		"MONOSPACE_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Basier Square": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Basier Square Mono": [
		"MONOSPACE_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Bould": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Calendas Plus": [
		"SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Cassannet Plus": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Chaney": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Geomanist": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Knile": [
		"SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"MUSETTA": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Noway": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Noway Round": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"PARKING": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Salome": [
		"DISPLAY_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Salome Deco": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Salome Fine": [
		"DISPLAY_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Salome Stencil": [
		"DISPLAY_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Sawton Bauhaus": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Sawton Circular": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Sawton Industrial": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Scilla": [
		"SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Silka": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Silka Mono": [
		"MONOSPACE_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Strawford": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Wotfard": [
		"SANS_SERIF_COLLECTION",
		"ATIPO_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Job Clarendon": [
		"SANS_SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Megazoid": [
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Megazoid Fill": [
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Megazoid Shade Left": [
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Megazoid Shade Right": [
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Nickel": [
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Nickel Gothic": [
		"SANS_SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Nickel Open Face": [
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Output Sans 2 Beta": [
		"SANS_SERIF_COLLECTION",
		"UI_FONTS_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Pomfret": [
		"SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Roslindale Extended": [
		"DISPLAY_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Warbler Text": [
		"SERIF_COLLECTION",
		"DJR_FONT_OF_THE_MONTH_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Apfel Grotezk": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Apfel Grotezk Brukt": [
		"DISPLAY_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"AUTHENTIC Sans": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Bagnard": [
		"SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Blackout 2AM": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Blackout Midnight": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Blackout Sunrise": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Butler": [
		"SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Butler Stencil": [
		"DISPLAY_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Cloitre": [
		"DISPLAY_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Cloitre Rounded": [
		"DISPLAY_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Cooper Hewitt": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Golos UI": [
		"SANS_SERIF_COLLECTION",
		"UI_FONTS_COLLECTION",
		"MULTIPLEXED_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Junction": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"League Mono": [
		"MONOSPACE_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Liberation Mono": [
		"MONOSPACE_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Liberation Sans": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Liberation Serif": [
		"SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Metropolis": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Open Sauce One": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Open Sauce Sans": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Open Sauce Two": [
		"SANS_SERIF_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"PT Root UI": [
		"SANS_SERIF_COLLECTION",
		"UI_FONTS_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Satoshi": [
		"SANS_SERIF_COLLECTION",
		"UI_FONTS_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"SuperDuper": [
		"SANS_SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Victor Mono": [
		"MONOSPACE_COLLECTION",
		"FREE_OPEN_COLLECTION"
	],
	"Acorn": [
		"DISPLAY_COLLECTION",
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"ALT Riviera": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"AUTHENTIC Classified": [
		"DISPLAY_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Bloyd": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Bureau Serif": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Cabrio": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Cartograph CF": [
		"MONOSPACE_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Crit": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"DaVinci": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Def Sans": [
		"SANS_SERIF_COLLECTION",
		"UI_FONTS_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Easy Grotesk": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Ernst": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"FL Prefere": [
		"SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Gangster Grotesk": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Gestura Text": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Greycliff CF": [
		"SANS_SERIF_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Gosh": [
		"DISPLAY_COLLECTION",
		"SANS_SERIF_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Henrietta": [
		"DISPLAY_COLLECTION",
		"SANS_SERIF_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"HEX Franklin": [
		"SANS_SERIF_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"MULTIPLEXED_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"HEX Franklin Tyght": [
		"SANS_SERIF_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"MULTIPLEXED_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Hop": [
		"SANS_SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Hypertext Display": [
		"DISPLAY_COLLECTION",
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Integral CF": [
		"DISPLAY_COLLECTION",
		"ALL_CAPS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Loretta": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Louche": [
		"DISPLAY_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Macabre": [
		"DISPLAY_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Marcin Antique": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"McQueen": [
		"SANS_SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"MD Nichrome": [
		"SANS_SERIF_COLLECTION",
		"DISPLAY_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Metra": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Micrograph": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"UI_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Mint Grotesk": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Mint Grotesk Display": [
		"DISPLAY_COLLECTION",
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"FUTURE_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Nicephore": [
		"DISPLAY_COLLECTION",
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Peridot PE": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Protest Grotesk": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Quasar": [
		"DISPLAY_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Resist Mono": [
		"MONOSPACE_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"SFT Schrifted Serif": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Softcore": [
		"SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Ufficio Display": [
		"DISPLAY_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	],
	"Ufficio Sans": [
		"SANS_SERIF_COLLECTION",
		"FRESH_FONTS_COLLECTION",
		"LICENSED_COLLECTION"
	]
};

