// This file is generated by yarn scan-fonts. Do not edit.
export default {
	"ALT Riviera": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				200,
				0.505493,
				1.025
			],
			[
				250,
				0.505493,
				1.025
			],
			[
				300,
				0.505493,
				1.025
			],
			[
				350,
				0.505493,
				1.025
			],
			[
				400,
				0.505493,
				1.025
			],
			[
				450,
				0.505493,
				1.025
			],
			[
				500,
				0.505493,
				1.025
			],
			[
				550,
				0.505493,
				1.025
			],
			[
				600,
				0.505493,
				1.025
			],
			[
				650,
				0.505493,
				1.025
			],
			[
				700,
				0.505493,
				1.025
			],
			[
				750,
				0.505493,
				1.025
			],
			[
				800,
				0.505493,
				1.025
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					200,
					800
				]
			}
		]
	},
	"AUTHENTIC Classified": {
		"features": [
		],
		"metrics": [
			[
				400,
				0.436393,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"AUTHENTIC Sans": {
		"features": [
		],
		"metrics": [
			[
				300,
				0.5322,
				1.2
			],
			[
				400,
				0.543367,
				1.2
			],
			[
				700,
				0.554667,
				1.2
			],
			[
				900,
				0.565833,
				1.2
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 900
			},
			{
				"weight": 300
			},
			{
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 900,
				"width": 75
			},
			{
				"weight": 300,
				"width": 75
			},
			{
				"width": 75
			}
		]
	},
	"Acorn": {
		"features": [
			"aalt",
			"calt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"ss01"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.5056,
				1.2
			],
			[
				150,
				0.5056,
				1.2
			],
			[
				200,
				0.5056,
				1.2
			],
			[
				250,
				0.5056,
				1.2
			],
			[
				300,
				0.5056,
				1.2
			],
			[
				350,
				0.5056,
				1.2
			],
			[
				400,
				0.5056,
				1.2
			],
			[
				450,
				0.5056,
				1.2
			],
			[
				500,
				0.5056,
				1.2
			],
			[
				550,
				0.5056,
				1.2
			],
			[
				600,
				0.5056,
				1.2
			],
			[
				650,
				0.5056,
				1.2
			],
			[
				700,
				0.5056,
				1.2
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					100,
					700
				]
			}
		]
	},
	"Apfel Grotezk": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"frac",
			"kern",
			"mark",
			"ordn",
			"sups"
		],
		"metrics": [
			[
				400,
				0.483387,
				1.08
			],
			[
				700,
				0.495213,
				1.08
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
			}
		]
	},
	"Apfel Grotezk Brukt": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"frac",
			"kern",
			"mark",
			"ordn",
			"sups"
		],
		"metrics": [
			[
				400,
				0.483387,
				1.08
			]
		],
		"variants": [
			{
			}
		]
	},
	"Archia": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.57698,
				1.2
			],
			[
				300,
				0.569493,
				1.2
			],
			[
				400,
				0.560953,
				1.2
			],
			[
				500,
				0.558987,
				1.2
			],
			[
				600,
				0.55788,
				1.2
			],
			[
				700,
				0.554293,
				1.2
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"weight": 100
			}
		]
	},
	"Argesta Display": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"metrics": [
			[
				400,
				0.521208,
				1
			]
		],
		"variants": [
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Argesta Hairline": {
		"featureGroups": [
			{
				"features": [
					"dlig"
				],
				"variants": [
					{
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"metrics": [
			[
				400,
				0.501624,
				1
			]
		],
		"variants": [
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Argesta Headline": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"metrics": [
			[
				400,
				0.521117,
				1
			]
		],
		"variants": [
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Argesta Text": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"metrics": [
			[
				400,
				0.566777,
				1
			],
			[
				700,
				0.579421,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Bagnard": {
		"features": [
			"cpsp",
			"kern",
			"liga"
		],
		"metrics": [
			[
				400,
				0.539609,
				1.200195
			]
		],
		"variants": [
			{
			}
		]
	},
	"Bariol": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"ornm",
			"pnum",
			"salt",
			"sinf",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.450244,
				1
			],
			[
				300,
				0.451061,
				1
			],
			[
				400,
				0.454993,
				1
			],
			[
				700,
				0.464199,
				1
			]
		],
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"Bariol Serif": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"ornm",
			"pnum",
			"salt",
			"sinf",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.4882,
				1
			],
			[
				300,
				0.490794,
				1
			],
			[
				400,
				0.49304,
				1
			],
			[
				700,
				0.49679,
				1
			]
		],
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"Basier Circle": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"kern",
			"mark",
			"sups"
		],
		"metrics": [
			[
				400,
				0.534,
				1
			],
			[
				500,
				0.53652,
				1
			],
			[
				600,
				0.53822,
				1
			],
			[
				700,
				0.539453,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Basier Circle Mono": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
					"kern"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"mark",
			"sups"
		],
		"metrics": [
			[
				400,
				0.618652,
				1
			],
			[
				500,
				0.618473,
				1
			],
			[
				600,
				0.618359,
				1
			],
			[
				700,
				0.618239,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Basier Square": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"kern",
			"mark",
			"sups"
		],
		"metrics": [
			[
				400,
				0.53408,
				1
			],
			[
				500,
				0.53656,
				1
			],
			[
				600,
				0.538213,
				1
			],
			[
				700,
				0.539413,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Basier Square Mono": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
					"kern"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"mark",
			"sups"
		],
		"metrics": [
			[
				400,
				0.618652,
				1
			],
			[
				500,
				0.618473,
				1
			],
			[
				600,
				0.618359,
				1
			],
			[
				700,
				0.618239,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Blackout 2AM": {
		"features": [
			"kern"
		],
		"metrics": [
			[
				400,
				0.576738,
				1
			]
		],
		"variants": [
			{
			}
		]
	},
	"Blackout Midnight": {
		"features": [
			"kern"
		],
		"metrics": [
			[
				400,
				0.524538,
				1
			]
		],
		"variants": [
			{
			}
		]
	},
	"Blackout Sunrise": {
		"features": [
			"kern"
		],
		"metrics": [
			[
				400,
				0.531829,
				1
			]
		],
		"variants": [
			{
			}
		]
	},
	"Bloyd": {
		"axes": {
			"slnt": [
				"Slant",
				-10,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12",
			"ss13",
			"ss14",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				200,
				0.497567,
				1
			],
			[
				250,
				0.497567,
				1
			],
			[
				300,
				0.497567,
				1
			],
			[
				350,
				0.497567,
				1
			],
			[
				400,
				0.497567,
				1
			],
			[
				450,
				0.497567,
				1
			],
			[
				500,
				0.497567,
				1
			],
			[
				550,
				0.497567,
				1
			],
			[
				600,
				0.497567,
				1
			],
			[
				650,
				0.497567,
				1
			],
			[
				700,
				0.497567,
				1
			],
			[
				750,
				0.497567,
				1
			],
			[
				800,
				0.497567,
				1
			],
			[
				850,
				0.497567,
				1
			],
			[
				900,
				0.497567,
				1
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					200,
					900
				]
			}
		]
	},
	"Bould": {
		"features": [
			"aalt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.483733,
				1
			],
			[
				200,
				0.49104,
				1
			],
			[
				300,
				0.49808,
				1
			],
			[
				400,
				0.502467,
				1
			],
			[
				500,
				0.50674,
				1
			],
			[
				600,
				0.5109,
				1
			],
			[
				700,
				0.51428,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Bureau Serif": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss10",
			"ss11",
			"subs",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				300,
				0.5185,
				1.43
			],
			[
				400,
				0.5263,
				1.43
			],
			[
				500,
				0.539913,
				1.43
			],
			[
				600,
				0.546653,
				1.43
			],
			[
				700,
				0.553547,
				1.43
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Butler": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"lnum",
			"onum",
			"ordn",
			"pnum",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				200,
				0.4592,
				1.2
			],
			[
				300,
				0.476487,
				1.2
			],
			[
				400,
				0.494487,
				1.2
			],
			[
				500,
				0.511953,
				1.2
			],
			[
				700,
				0.52938,
				1.2
			],
			[
				800,
				0.547047,
				1.2
			],
			[
				900,
				0.568607,
				1.2
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"weight": 200
			},
			{
			}
		]
	},
	"Butler Stencil": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"lnum",
			"onum",
			"ordn",
			"pnum",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				200,
				0.459167,
				1.2
			],
			[
				300,
				0.476573,
				1.2
			],
			[
				400,
				0.494407,
				1.2
			],
			[
				500,
				0.511987,
				1.2
			],
			[
				700,
				0.52938,
				1.2
			],
			[
				800,
				0.547033,
				1.2
			],
			[
				900,
				0.56856,
				1.2
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"weight": 200
			},
			{
			}
		]
	},
	"Cabrio": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							300,
							950
						]
					}
				]
			},
			{
				"features": [
					"ss02"
				],
				"variants": [
					{
						"weight": [
							300,
							950
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				300,
				0.480913,
				1.27
			],
			[
				350,
				0.480913,
				1.27
			],
			[
				400,
				0.480913,
				1.27
			],
			[
				450,
				0.480913,
				1.27
			],
			[
				500,
				0.480913,
				1.27
			],
			[
				550,
				0.480913,
				1.27
			],
			[
				600,
				0.480913,
				1.27
			],
			[
				650,
				0.480913,
				1.27
			],
			[
				700,
				0.480913,
				1.27
			],
			[
				750,
				0.480913,
				1.27
			],
			[
				800,
				0.480913,
				1.27
			],
			[
				850,
				0.480913,
				1.27
			],
			[
				900,
				0.480913,
				1.27
			],
			[
				950,
				0.480913,
				1.27
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					300,
					950
				]
			},
			{
				"weight": [
					300,
					950
				]
			}
		]
	},
	"Calendas Plus": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"ornm",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"metrics": [
			[
				400,
				0.509167,
				1
			],
			[
				700,
				0.526735,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Cartograph CF": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 800
					},
					{
						"italic": 1,
						"weight": 200
					},
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			},
			{
				"features": [
					"ss03"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 600
					},
					{
						"weight": 800
					},
					{
						"weight": 200
					},
					{
						"weight": 900
					},
					{
						"weight": 300
					},
					{
					},
					{
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss05",
			"sups",
			"vert",
			"vrt2"
		],
		"metrics": [
			[
				100,
				0.614746,
				1.199707
			],
			[
				200,
				0.614746,
				1.199707
			],
			[
				300,
				0.614746,
				1.199707
			],
			[
				400,
				0.614746,
				1.199707
			],
			[
				600,
				0.614746,
				1.199707
			],
			[
				700,
				0.614746,
				1.199707
			],
			[
				800,
				0.614746,
				1.199707
			],
			[
				900,
				0.614746,
				1.199707
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"Cassannet Plus": {
		"features": [
			"aalt",
			"dlig",
			"kern",
			"ornm",
			"salt",
			"sups"
		],
		"metrics": [
			[
				100,
				0.530667,
				1
			],
			[
				300,
				0.540495,
				1
			],
			[
				400,
				0.549089,
				1
			],
			[
				700,
				0.555277,
				1
			],
			[
				900,
				0.567484,
				1
			],
			[
				950,
				0.595212,
				1
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
			},
			{
				"weight": 100
			},
			{
				"weight": 950
			}
		]
	},
	"Chaney": {
		"features": [
			"aalt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"sups"
		],
		"metrics": [
			[
				400,
				0.690107,
				1
			]
		],
		"variants": [
			{
				"width": 125
			},
			{
			},
			{
				"width": 200
			},
			{
				"width": 112.5
			}
		]
	},
	"Cloitre": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05"
		],
		"metrics": [
			[
				400,
				0.28288,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Cloitre Rounded": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05"
		],
		"metrics": [
			[
				400,
				0.28288,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Cooper Hewitt": {
		"features": [
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"numr",
			"sinf",
			"ss01",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.465798,
				1.299805
			],
			[
				300,
				0.481465,
				1.299805
			],
			[
				400,
				0.491475,
				1.299805
			],
			[
				500,
				0.501426,
				1.299805
			],
			[
				600,
				0.511325,
				1.299805
			],
			[
				700,
				0.520339,
				1.299805
			],
			[
				900,
				0.528929,
				1.299805
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
			}
		]
	},
	"Crit": {
		"features": [
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"subs",
			"sups"
		],
		"metrics": [
			[
				200,
				0.526667,
				1.296
			],
			[
				300,
				0.531113,
				1.296
			],
			[
				400,
				0.537527,
				1.296
			],
			[
				500,
				0.543753,
				1.296
			],
			[
				600,
				0.550227,
				1.296
			],
			[
				700,
				0.56242,
				1.296
			],
			[
				800,
				0.583033,
				1.296
			],
			[
				900,
				0.604167,
				1.296
			]
		],
		"variants": [
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"italic": 1
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 600
			}
		]
	},
	"DaVinci": {
		"featureGroups": [
			{
				"features": [
					"ccmp",
					"mark",
					"mkmk"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 900
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					},
					{
						"weight": 100
					}
				]
			},
			{
				"features": [
					"dnom",
					"frac",
					"numr",
					"sinf",
					"ss01",
					"ss02",
					"ss03",
					"subs",
					"sups"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"dlig",
			"kern",
			"liga",
			"lnum",
			"onum",
			"pnum",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.4665,
				1.2
			],
			[
				300,
				0.475427,
				1.2
			],
			[
				400,
				0.483867,
				1.2
			],
			[
				500,
				0.495213,
				1.2
			],
			[
				600,
				0.506487,
				1.2
			],
			[
				700,
				0.517627,
				1.2
			],
			[
				900,
				0.52874,
				1.2
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Def Sans": {
		"axes": {
			"slnt": [
				"Slant",
				-8,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.518193,
				1
			],
			[
				150,
				0.518193,
				1
			],
			[
				200,
				0.518193,
				1
			],
			[
				250,
				0.518193,
				1
			],
			[
				300,
				0.518193,
				1
			],
			[
				350,
				0.518193,
				1
			],
			[
				400,
				0.518193,
				1
			],
			[
				450,
				0.518193,
				1
			],
			[
				500,
				0.518193,
				1
			],
			[
				550,
				0.518193,
				1
			],
			[
				600,
				0.518193,
				1
			],
			[
				650,
				0.518193,
				1
			],
			[
				700,
				0.518193,
				1
			],
			[
				750,
				0.518193,
				1
			],
			[
				800,
				0.518193,
				1
			],
			[
				850,
				0.518193,
				1
			],
			[
				900,
				0.518193,
				1
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					100,
					900
				],
				"width": [
					75,
					100
				]
			}
		]
	},
	"Easy Grotesk": {
		"axes": {
			"slnt": [
				"Slant",
				0,
				10,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"fwid",
			"kern",
			"liga",
			"lnum",
			"locl",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss10",
			"ss11",
			"ss12",
			"ss13",
			"ss14",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				200,
				0.568387,
				1.4
			],
			[
				250,
				0.568387,
				1.4
			],
			[
				300,
				0.568387,
				1.4
			],
			[
				350,
				0.568387,
				1.4
			],
			[
				400,
				0.568387,
				1.4
			],
			[
				450,
				0.568387,
				1.4
			],
			[
				500,
				0.568387,
				1.4
			],
			[
				550,
				0.568387,
				1.4
			],
			[
				600,
				0.568387,
				1.4
			],
			[
				650,
				0.568387,
				1.4
			],
			[
				700,
				0.568387,
				1.4
			],
			[
				750,
				0.568387,
				1.4
			],
			[
				800,
				0.568387,
				1.4
			],
			[
				850,
				0.568387,
				1.4
			],
			[
				900,
				0.568387,
				1.4
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					200,
					900
				]
			}
		]
	},
	"Ernst": {
		"features": [
			"aalt",
			"c2sc",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"salt",
			"sinf",
			"smcp",
			"ss01",
			"ss02",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.537047,
				0.87
			],
			[
				150,
				0.537047,
				0.87
			],
			[
				200,
				0.537047,
				0.87
			],
			[
				250,
				0.537047,
				0.87
			],
			[
				300,
				0.537047,
				0.87
			],
			[
				350,
				0.537047,
				0.87
			],
			[
				400,
				0.537047,
				0.87
			],
			[
				450,
				0.537047,
				0.87
			],
			[
				500,
				0.537047,
				0.87
			],
			[
				550,
				0.537047,
				0.87
			],
			[
				600,
				0.537047,
				0.87
			],
			[
				650,
				0.537047,
				0.87
			],
			[
				700,
				0.537047,
				0.87
			],
			[
				750,
				0.537047,
				0.87
			],
			[
				800,
				0.537047,
				0.87
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					800
				]
			},
			{
				"weight": [
					100,
					800
				]
			}
		]
	},
	"FL Prefere": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"kern",
			"liga",
			"mark"
		],
		"isVariable": true,
		"metrics": [
			[
				300,
				0.477722,
				1.2875
			],
			[
				350,
				0.477722,
				1.2875
			],
			[
				400,
				0.477722,
				1.2875
			],
			[
				450,
				0.477722,
				1.2875
			],
			[
				500,
				0.477722,
				1.2875
			],
			[
				550,
				0.477722,
				1.2875
			],
			[
				600,
				0.477722,
				1.2875
			],
			[
				650,
				0.477722,
				1.2875
			],
			[
				700,
				0.477722,
				1.2875
			],
			[
				750,
				0.477722,
				1.2875
			],
			[
				800,
				0.477722,
				1.2875
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					300,
					800
				]
			},
			{
				"italic": 1,
				"weight": [
					300,
					800
				]
			}
		]
	},
	"Gangster Grotesk": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"ss01",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				300,
				0.51702,
				1.6
			],
			[
				400,
				0.52874,
				1.6
			],
			[
				700,
				0.54232,
				1.6
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
			}
		]
	},
	"Geomanist": {
		"features": [
			"aalt",
			"case",
			"frac",
			"kern",
			"liga",
			"ordn",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.477354,
				1
			],
			[
				200,
				0.482982,
				1
			],
			[
				300,
				0.488493,
				1
			],
			[
				400,
				0.494593,
				1
			],
			[
				450,
				0.502816,
				1
			],
			[
				500,
				0.51057,
				1
			],
			[
				700,
				0.513294,
				1
			],
			[
				900,
				0.528796,
				1
			],
			[
				950,
				0.534427,
				1
			]
		],
		"variants": [
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 450
			},
			{
				"weight": 450
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"weight": 950
			}
		]
	},
	"Gestura Text": {
		"featureGroups": [
			{
				"features": [
					"mkmk",
					"ss04",
					"ss05",
					"ss06"
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							100,
							900
						]
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"weight": [
							100,
							900
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"subs",
			"sups",
			"titl",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.51624,
				1.15
			],
			[
				150,
				0.520076,
				1.15
			],
			[
				200,
				0.523912,
				1.15
			],
			[
				250,
				0.528705,
				1.15
			],
			[
				300,
				0.533498,
				1.15
			],
			[
				350,
				0.53877,
				1.15
			],
			[
				400,
				0.544043,
				1.15
			],
			[
				450,
				0.548358,
				1.15
			],
			[
				500,
				0.552672,
				1.15
			],
			[
				550,
				0.556986,
				1.15
			],
			[
				600,
				0.561301,
				1.15
			],
			[
				650,
				0.571369,
				1.15
			],
			[
				700,
				0.581438,
				1.15
			],
			[
				750,
				0.589108,
				1.15
			],
			[
				800,
				0.596779,
				1.15
			],
			[
				850,
				0.604449,
				1.15
			],
			[
				900,
				0.61212,
				1.15
			]
		],
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					900
				]
			},
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Golos UI": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"cpsp",
			"frac",
			"kern",
			"ordn",
			"sups"
		],
		"isVariable": true,
		"metrics": [
			[
				400,
				0.510487,
				1.2
			],
			[
				450,
				0.510487,
				1.2
			],
			[
				500,
				0.510487,
				1.2
			],
			[
				550,
				0.510487,
				1.2
			],
			[
				600,
				0.510487,
				1.2
			],
			[
				650,
				0.510487,
				1.2
			],
			[
				700,
				0.510487,
				1.2
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					400,
					700
				]
			}
		]
	},
	"Gosh": {
		"features": [
			"aalt",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"pnum",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"tnum"
		],
		"metrics": [
			[
				700,
				0.664713,
				1.2
			],
			[
				800,
				0.6606,
				1.2
			],
			[
				900,
				0.657373,
				1.2
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 900,
				"width": 75
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 800,
				"width": 75
			},
			{
				"weight": 800
			},
			{
				"weight": 900,
				"width": 62.5
			},
			{
				"weight": 700,
				"width": 62.5
			},
			{
				"weight": 800,
				"width": 62.5
			},
			{
				"weight": 900,
				"width": 150
			},
			{
				"weight": 700,
				"width": 150
			},
			{
				"weight": 800,
				"width": 150
			},
			{
				"weight": 900,
				"width": 87.5
			},
			{
				"weight": 700,
				"width": 87.5
			},
			{
				"weight": 800,
				"width": 87.5
			},
			{
				"weight": 900,
				"width": 125
			},
			{
				"weight": 700,
				"width": 125
			},
			{
				"weight": 800,
				"width": 125
			}
		]
	},
	"Greycliff CF": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"ss01",
			"ss02",
			"ss03",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.496527,
				1.199707
			],
			[
				200,
				0.498851,
				1.199707
			],
			[
				300,
				0.500957,
				1.199707
			],
			[
				400,
				0.502998,
				1.199707
			],
			[
				500,
				0.506286,
				1.199707
			],
			[
				600,
				0.509219,
				1.199707
			],
			[
				700,
				0.514606,
				1.199707
			],
			[
				800,
				0.517129,
				1.199707
			],
			[
				900,
				0.519723,
				1.199707
			]
		],
		"variants": [
			{
				"oblique": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"oblique": 1,
				"weight": 600
			},
			{
				"weight": 600
			},
			{
				"oblique": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"oblique": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"oblique": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"oblique": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"oblique": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
				"oblique": 1
			},
			{
			},
			{
				"oblique": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"HEX Franklin": {
		"features": [
			"calt",
			"case",
			"kern",
			"mark",
			"pnum",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss07",
			"ss08",
			"ss15",
			"ss16",
			"ss17",
			"titl",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				1,
				0.5442,
				1.15
			],
			[
				50,
				0.5442,
				1.15
			],
			[
				100,
				0.5442,
				1.15
			],
			[
				150,
				0.5442,
				1.15
			],
			[
				200,
				0.5442,
				1.15
			],
			[
				250,
				0.5442,
				1.15
			],
			[
				300,
				0.5442,
				1.15
			],
			[
				350,
				0.5442,
				1.15
			],
			[
				400,
				0.5442,
				1.15
			],
			[
				450,
				0.5442,
				1.15
			],
			[
				500,
				0.5442,
				1.15
			],
			[
				550,
				0.5442,
				1.15
			],
			[
				600,
				0.5442,
				1.15
			],
			[
				650,
				0.5442,
				1.15
			],
			[
				700,
				0.5442,
				1.15
			],
			[
				750,
				0.5442,
				1.15
			],
			[
				800,
				0.5442,
				1.15
			],
			[
				850,
				0.552165,
				1.15
			],
			[
				900,
				0.560132,
				1.15
			],
			[
				950,
				0.5681,
				1.15
			],
			[
				1000,
				0.576067,
				1.15
			]
		],
		"variants": [
			{
				"weight": [
					1,
					1000
				],
				"width": [
					60,
					120
				]
			}
		]
	},
	"HEX Franklin Tyght": {
		"axes": {
			"NOTC": [
				"Not Touching",
				0,
				1,
				0,
				0.01
			],
			"TYTE": [
				"Tyght",
				-100,
				0,
				-100,
				0.01
			]
		},
		"features": [
			"kern",
			"mark",
			"ss04",
			"ss05",
			"ss08",
			"ss15",
			"titl"
		],
		"isVariable": true,
		"metrics": [
			[
				800,
				0.51404,
				1.15
			]
		],
		"variants": [
			{
				"weight": 800,
				"width": [
					60,
					100
				]
			}
		]
	},
	"Henrietta": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"clig",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08"
		],
		"metrics": [
			[
				300,
				0.522447,
				1.2
			],
			[
				400,
				0.528047,
				1.2
			],
			[
				500,
				0.536773,
				1.2
			],
			[
				600,
				0.55238,
				1.2
			],
			[
				700,
				0.56434,
				1.2
			],
			[
				900,
				0.571813,
				1.2
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 900,
				"width": 75
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 300,
				"width": 75
			},
			{
				"weight": 500,
				"width": 75
			},
			{
				"width": 75
			},
			{
				"weight": 600,
				"width": 75
			}
		]
	},
	"Hop": {
		"axes": {
			"cstm": [
				"Rounded",
				0,
				100,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.269087,
				0.945
			],
			[
				150,
				0.269087,
				0.945
			],
			[
				200,
				0.269087,
				0.945
			],
			[
				250,
				0.269087,
				0.945
			],
			[
				300,
				0.269087,
				0.945
			],
			[
				350,
				0.269087,
				0.945
			],
			[
				400,
				0.269087,
				0.945
			],
			[
				450,
				0.269087,
				0.945
			],
			[
				500,
				0.269087,
				0.945
			],
			[
				550,
				0.269087,
				0.945
			],
			[
				600,
				0.269087,
				0.945
			],
			[
				650,
				0.269087,
				0.945
			],
			[
				700,
				0.269087,
				0.945
			],
			[
				750,
				0.269087,
				0.945
			],
			[
				800,
				0.269087,
				0.945
			],
			[
				850,
				0.269087,
				0.945
			],
			[
				900,
				0.269087,
				0.945
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Hypertext Display": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.461033,
				1.2
			],
			[
				300,
				0.47356,
				1.2
			],
			[
				400,
				0.48192,
				1.2
			],
			[
				500,
				0.490287,
				1.2
			],
			[
				700,
				0.511207,
				1.2
			],
			[
				900,
				0.523733,
				1.2
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Integral CF": {
		"features": [
			"aalt",
			"cpsp",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01"
		],
		"metrics": [
			[
				400,
				0.647949,
				1.200195
			],
			[
				500,
				0.659014,
				1.200195
			],
			[
				600,
				0.670059,
				1.200195
			],
			[
				700,
				0.680781,
				1.200195
			],
			[
				800,
				0.691885,
				1.200195
			],
			[
				900,
				0.702904,
				1.200195
			]
		],
		"variants": [
			{
				"oblique": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"oblique": 1,
				"weight": 600
			},
			{
				"weight": 600
			},
			{
				"oblique": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"oblique": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"oblique": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
				"oblique": 1
			},
			{
			}
		]
	},
	"Job Clarendon": {
		"features": [
			"aalt",
			"calt",
			"case",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"zero"
		],
		"metrics": [
			[
				1,
				0.17314,
				1.2
			]
		],
		"variants": [
			{
				"weight": 1,
				"width": 62.5
			},
			{
				"weight": 1,
				"width": 75
			},
			{
				"weight": 1,
				"width": 50
			}
		]
	},
	"Junction": {
		"features": [
			"aalt",
			"kern",
			"liga",
			"lnum"
		],
		"metrics": [
			[
				300,
				0.519876,
				1
			],
			[
				400,
				0.531947,
				1
			],
			[
				700,
				0.540273,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
			}
		]
	},
	"Knile": {
		"features": [
			"aalt",
			"calt",
			"cpsp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.543193,
				1
			],
			[
				200,
				0.548278,
				1
			],
			[
				300,
				0.55168,
				1
			],
			[
				400,
				0.559609,
				1
			],
			[
				500,
				0.569391,
				1
			],
			[
				600,
				0.585163,
				1
			],
			[
				700,
				0.601139,
				1
			],
			[
				900,
				0.619632,
				1
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"League Mono": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"mark",
			"mkmk",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.71,
				1.075
			],
			[
				200,
				0.71,
				1.075
			],
			[
				300,
				0.71,
				1.075
			],
			[
				400,
				0.71,
				1.075
			],
			[
				500,
				0.71,
				1.075
			],
			[
				600,
				0.71,
				1.075
			],
			[
				700,
				0.71,
				1.075
			],
			[
				800,
				0.71,
				1.075
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": 700,
				"width": 112.5
			},
			{
				"weight": 700,
				"width": 50
			},
			{
				"weight": 800,
				"width": 50
			},
			{
				"weight": 300,
				"width": 50
			},
			{
				"weight": 500,
				"width": 50
			},
			{
				"width": 50
			},
			{
				"weight": 600,
				"width": 50
			},
			{
				"weight": 100,
				"width": 50
			},
			{
				"weight": 200,
				"width": 50
			},
			{
				"weight": 700,
				"width": 200
			},
			{
				"weight": 800,
				"width": 200
			},
			{
				"weight": 300,
				"width": 200
			},
			{
				"weight": 500,
				"width": 200
			},
			{
				"width": 200
			},
			{
				"weight": 600,
				"width": 200
			},
			{
				"weight": 100,
				"width": 200
			},
			{
				"weight": 200,
				"width": 200
			},
			{
				"weight": 800,
				"width": 112.5
			},
			{
				"weight": 300,
				"width": 112.5
			},
			{
				"weight": 500,
				"width": 112.5
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 800,
				"width": 75
			},
			{
				"weight": 300,
				"width": 75
			},
			{
				"weight": 500,
				"width": 75
			},
			{
				"width": 75
			},
			{
				"weight": 600,
				"width": 75
			},
			{
				"weight": 100,
				"width": 75
			},
			{
				"weight": 200,
				"width": 75
			},
			{
				"width": 112.5
			},
			{
				"weight": 600,
				"width": 112.5
			},
			{
				"weight": 100,
				"width": 112.5
			},
			{
				"weight": 200,
				"width": 112.5
			},
			{
				"weight": 700,
				"width": 150
			},
			{
				"weight": 800,
				"width": 150
			},
			{
				"weight": 300,
				"width": 150
			},
			{
				"weight": 500,
				"width": 150
			},
			{
				"width": 150
			},
			{
				"weight": 600,
				"width": 150
			},
			{
				"weight": 100,
				"width": 150
			},
			{
				"weight": 200,
				"width": 150
			}
		]
	},
	"Liberation Mono": {
		"features": [
		],
		"metrics": [
			[
				400,
				0.600098,
				0.80127
			],
			[
				700,
				0.600098,
				0.842285
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Liberation Sans": {
		"features": [
			"ccmp",
			"kern"
		],
		"metrics": [
			[
				400,
				0.513809,
				1.088379
			],
			[
				700,
				0.542702,
				1.088379
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Liberation Serif": {
		"features": [
			"ccmp",
			"kern"
		],
		"metrics": [
			[
				400,
				0.485898,
				1.059082
			],
			[
				700,
				0.508874,
				1.042969
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Loretta": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"sinf",
			"subs",
			"sups"
		],
		"metrics": [
			[
				300,
				0.496793,
				1.16
			],
			[
				400,
				0.508647,
				1.16
			],
			[
				500,
				0.52054,
				1.16
			],
			[
				600,
				0.532433,
				1.16
			],
			[
				700,
				0.544327,
				1.16
			],
			[
				800,
				0.55618,
				1.16
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Louche": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"numr",
			"onum",
			"ordn",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"subs",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				400,
				0.253527,
				1.135
			],
			[
				500,
				0.25913,
				1.135
			],
			[
				600,
				0.265617,
				1.135
			],
			[
				700,
				0.273283,
				1.135
			],
			[
				900,
				0.280487,
				1.135
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			}
		]
	},
	"MD Nichrome": {
		"axes": {
			"slnt": [
				"Slant",
				-10,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cv01",
			"cv02",
			"cv03",
			"cv04",
			"cv05",
			"cv06",
			"cv07",
			"cv08",
			"cv09",
			"cv10",
			"cv11",
			"cv12",
			"cv13",
			"cv14",
			"cv15",
			"cv16",
			"cv17",
			"cv18",
			"cv19",
			"cv20",
			"cv21",
			"cv22",
			"cv23",
			"cv24",
			"cv25",
			"cv26",
			"cv27",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.385373,
				1.2
			],
			[
				150,
				0.38809,
				1.2
			],
			[
				200,
				0.390807,
				1.2
			],
			[
				250,
				0.394125,
				1.2
			],
			[
				300,
				0.397443,
				1.2
			],
			[
				350,
				0.401668,
				1.2
			],
			[
				400,
				0.405893,
				1.2
			],
			[
				450,
				0.411023,
				1.2
			],
			[
				500,
				0.416153,
				1.2
			],
			[
				550,
				0.419853,
				1.2
			],
			[
				600,
				0.423553,
				1.2
			],
			[
				650,
				0.427253,
				1.2
			],
			[
				700,
				0.430953,
				1.2
			],
			[
				750,
				0.438631,
				1.2
			],
			[
				800,
				0.44631,
				1.2
			],
			[
				850,
				0.452672,
				1.2
			],
			[
				900,
				0.459033,
				1.2
			]
		],
		"variants": [
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"MUSETTA": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"metrics": [
			[
				400,
				0.393847,
				1
			]
		],
		"variants": [
			{
			}
		]
	},
	"Macabre": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"kern",
			"liga",
			"mark",
			"mkmk"
		],
		"metrics": [
			[
				400,
				0.326453,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Marcin Antique": {
		"featureGroups": [
			{
				"features": [
					"ss08"
				],
				"variants": [
					{
						"weight": 900
					},
					{
						"weight": 700
					},
					{
						"weight": 450
					},
					{
						"weight": 800
					},
					{
						"weight": 200
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					},
					{
						"weight": 950
					},
					{
						"weight": 100
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 450
					},
					{
						"italic": 1,
						"weight": 800
					},
					{
						"italic": 1,
						"weight": 200
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 950
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss07",
			"subs",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.4834,
				1.223
			],
			[
				200,
				0.4915,
				1.223
			],
			[
				300,
				0.506533,
				1.223
			],
			[
				400,
				0.531167,
				1.223
			],
			[
				450,
				0.520247,
				1.223
			],
			[
				500,
				0.533807,
				1.223
			],
			[
				600,
				0.538727,
				1.223
			],
			[
				700,
				0.542433,
				1.223
			],
			[
				800,
				0.608613,
				1.223
			],
			[
				900,
				0.547293,
				1.223
			],
			[
				950,
				0.68356,
				1.223
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 450
			},
			{
				"italic": 1,
				"weight": 450
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 950
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"McQueen": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"metrics": [
			[
				200,
				0.458847,
				1.2
			],
			[
				300,
				0.4695,
				1.2
			],
			[
				400,
				0.479027,
				1.2
			],
			[
				500,
				0.49332,
				1.2
			],
			[
				600,
				0.51078,
				1.2
			],
			[
				700,
				0.524487,
				1.2
			],
			[
				800,
				0.540027,
				1.2
			],
			[
				900,
				0.555693,
				1.2
			],
			[
				1000,
				0.574353,
				1.2
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 1000
			},
			{
				"italic": 1,
				"weight": 1000
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			}
		]
	},
	"Megazoid": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"metrics": [
			[
				400,
				0.636133,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Megazoid Fill": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"metrics": [
			[
				400,
				0.636133,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Megazoid Shade Left": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"metrics": [
			[
				400,
				0.636133,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Megazoid Shade Right": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"metrics": [
			[
				400,
				0.636133,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Metra": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"subs",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				400,
				0.537069,
				1.25
			],
			[
				500,
				0.545403,
				1.25
			],
			[
				700,
				0.552132,
				1.25
			],
			[
				800,
				0.56484,
				1.25
			],
			[
				900,
				0.57259,
				1.25
			],
			[
				950,
				0.585042,
				1.25
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 950
			}
		]
	},
	"Metropolis": {
		"features": [
			"kern",
			"mark",
			"mkmk"
		],
		"metrics": [
			[
				100,
				0.527939,
				1
			],
			[
				200,
				0.535768,
				1
			],
			[
				300,
				0.54388,
				1
			],
			[
				400,
				0.551712,
				1
			],
			[
				500,
				0.55696,
				1
			],
			[
				600,
				0.562409,
				1
			],
			[
				700,
				0.567718,
				1
			],
			[
				800,
				0.573125,
				1
			],
			[
				900,
				0.578343,
				1
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Micrograph": {
		"features": [
			"aalt",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"rlig",
			"sinf",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.520027,
				1.3
			],
			[
				150,
				0.520027,
				1.3
			],
			[
				200,
				0.520027,
				1.3
			],
			[
				250,
				0.520027,
				1.3
			],
			[
				300,
				0.520027,
				1.3
			],
			[
				350,
				0.520027,
				1.3
			],
			[
				400,
				0.520027,
				1.3
			],
			[
				450,
				0.520027,
				1.3
			],
			[
				500,
				0.520027,
				1.3
			],
			[
				550,
				0.520027,
				1.3
			],
			[
				600,
				0.520027,
				1.3
			],
			[
				650,
				0.520027,
				1.3
			],
			[
				700,
				0.520027,
				1.3
			],
			[
				750,
				0.520027,
				1.3
			],
			[
				800,
				0.520027,
				1.3
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					800
				]
			},
			{
				"weight": [
					100,
					800
				]
			}
		]
	},
	"Mint Grotesk": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.521827,
				1.3
			],
			[
				300,
				0.529853,
				1.3
			],
			[
				400,
				0.539893,
				1.3
			],
			[
				500,
				0.55294,
				1.3
			],
			[
				700,
				0.568047,
				1.3
			],
			[
				800,
				0.588247,
				1.3
			],
			[
				900,
				0.606687,
				1.3
			],
			[
				950,
				0.623173,
				1.3
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 950
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Mint Grotesk Display": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.575327,
				1.3
			],
			[
				300,
				0.582433,
				1.3
			],
			[
				400,
				0.591207,
				1.3
			],
			[
				500,
				0.602493,
				1.3
			],
			[
				700,
				0.61552,
				1.3
			],
			[
				800,
				0.632133,
				1.3
			],
			[
				900,
				0.647153,
				1.3
			],
			[
				950,
				0.660713,
				1.3
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 950
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Nicephore": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dlig",
			"dnom",
			"frac",
			"hist",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				0,
				0.729447,
				1.2
			],
			[
				50,
				0.729447,
				1.2
			],
			[
				100,
				0.729447,
				1.2
			],
			[
				150,
				0.729447,
				1.2
			],
			[
				200,
				0.729447,
				1.2
			],
			[
				250,
				0.729447,
				1.2
			],
			[
				300,
				0.729447,
				1.2
			],
			[
				350,
				0.729447,
				1.2
			],
			[
				400,
				0.729447,
				1.2
			],
			[
				450,
				0.729447,
				1.2
			],
			[
				500,
				0.729447,
				1.2
			],
			[
				550,
				0.729447,
				1.2
			],
			[
				600,
				0.729447,
				1.2
			],
			[
				650,
				0.729447,
				1.2
			],
			[
				700,
				0.729447,
				1.2
			],
			[
				750,
				0.729447,
				1.2
			],
			[
				800,
				0.729447,
				1.2
			],
			[
				850,
				0.729447,
				1.2
			],
			[
				900,
				0.729447,
				1.2
			],
			[
				950,
				0.729447,
				1.2
			],
			[
				1000,
				0.729447,
				1.2
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					0,
					1000
				]
			}
		]
	},
	"Nickel": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02"
		],
		"metrics": [
			[
				400,
				0.71656,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Nickel Gothic": {
		"axes": {
			"slnt": [
				"Slant",
				-15,
				15,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06"
		],
		"isVariable": true,
		"metrics": [
			[
				400,
				0.62864,
				1.2
			]
		],
		"variants": [
			{
			},
			{
				"width": 125
			},
			{
				"width": 150
			},
			{
				"width": [
					100,
					150
				]
			}
		]
	},
	"Nickel Open Face": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02"
		],
		"metrics": [
			[
				400,
				0.71656,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Noway": {
		"features": [
			"aalt",
			"dlig",
			"frac",
			"kern",
			"liga",
			"ordn",
			"sups",
			"tnum",
			"zero"
		],
		"metrics": [
			[
				100,
				0.459639,
				1
			],
			[
				300,
				0.47249,
				1
			],
			[
				400,
				0.486331,
				1
			],
			[
				500,
				0.496475,
				1
			],
			[
				700,
				0.507813,
				1
			]
		],
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"italic": 1
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Noway Round": {
		"features": [
			"kern"
		],
		"metrics": [
			[
				100,
				0.461167,
				1
			],
			[
				300,
				0.473967,
				1
			],
			[
				400,
				0.486567,
				1
			],
			[
				500,
				0.497973,
				1
			],
			[
				700,
				0.508927,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Open Sauce One": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"weight": 900
					},
					{
						"weight": 700
					},
					{
						"weight": 800
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
					"pnum",
					"tnum"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 800
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn"
		],
		"metrics": [
			[
				300,
				0.544053,
				1.237
			],
			[
				400,
				0.55406,
				1.237
			],
			[
				500,
				0.560693,
				1.237
			],
			[
				600,
				0.562867,
				1.237
			],
			[
				700,
				0.567387,
				1.237
			],
			[
				800,
				0.571787,
				1.237
			],
			[
				900,
				0.576193,
				1.237
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Open Sauce Sans": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"pnum",
			"tnum"
		],
		"metrics": [
			[
				300,
				0.544053,
				1.237
			],
			[
				400,
				0.55406,
				1.237
			],
			[
				500,
				0.560693,
				1.237
			],
			[
				600,
				0.562867,
				1.237
			],
			[
				700,
				0.567387,
				1.237
			],
			[
				800,
				0.571787,
				1.237
			],
			[
				900,
				0.576193,
				1.237
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Open Sauce Two": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"pnum",
			"tnum"
		],
		"metrics": [
			[
				300,
				0.544053,
				1.237
			],
			[
				400,
				0.55406,
				1.237
			],
			[
				500,
				0.560693,
				1.237
			],
			[
				600,
				0.562867,
				1.237
			],
			[
				700,
				0.567387,
				1.237
			],
			[
				800,
				0.571787,
				1.237
			],
			[
				900,
				0.576193,
				1.237
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Output Sans 2 Beta": {
		"axes": {
			"GRAD": [
				"Grade",
				0,
				10,
				0,
				0.01
			],
			"TERM": [
				"Terminals",
				-1,
				1,
				0,
				0.01
			],
			"opsz": [
				"Optical size",
				10,
				48,
				48,
				0.01
			],
			"slnt": [
				"Slant",
				-13,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"rlig",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07"
		],
		"isVariable": true,
		"metrics": [
			[
				1,
				0.471953,
				1.2
			],
			[
				50,
				0.471953,
				1.2
			],
			[
				100,
				0.471953,
				1.2
			],
			[
				150,
				0.471953,
				1.2
			],
			[
				200,
				0.471953,
				1.2
			],
			[
				250,
				0.471953,
				1.2
			],
			[
				300,
				0.471953,
				1.2
			],
			[
				350,
				0.471953,
				1.2
			],
			[
				400,
				0.471953,
				1.2
			],
			[
				450,
				0.471953,
				1.2
			],
			[
				500,
				0.471953,
				1.2
			],
			[
				550,
				0.471953,
				1.2
			],
			[
				600,
				0.471953,
				1.2
			],
			[
				650,
				0.471953,
				1.2
			],
			[
				700,
				0.471953,
				1.2
			],
			[
				750,
				0.471953,
				1.2
			],
			[
				800,
				0.471953,
				1.2
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					1,
					800
				],
				"width": [
					75,
					125
				]
			}
		]
	},
	"PARKING": {
		"features": [
			"aalt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"sups"
		],
		"metrics": [
			[
				400,
				0.447028,
				1
			]
		],
		"variants": [
			{
			}
		]
	},
	"PT Root UI": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"cpsp",
			"dlig",
			"dnom",
			"frac",
			"hist",
			"kern",
			"liga",
			"numr",
			"ordn",
			"pnum",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				300,
				0.51138,
				1.2
			],
			[
				350,
				0.511353,
				1.2
			],
			[
				400,
				0.511327,
				1.2
			],
			[
				450,
				0.51132,
				1.2
			],
			[
				500,
				0.511313,
				1.2
			],
			[
				550,
				0.51131,
				1.2
			],
			[
				600,
				0.511307,
				1.2
			],
			[
				650,
				0.511303,
				1.2
			],
			[
				700,
				0.5113,
				1.2
			]
		],
		"variants": [
			{
				"weight": [
					300,
					700
				]
			}
		]
	},
	"Peridot PE": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"rvrn",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.493987,
				1.23
			],
			[
				150,
				0.499106,
				1.23
			],
			[
				200,
				0.504225,
				1.23
			],
			[
				250,
				0.509343,
				1.23
			],
			[
				300,
				0.514461,
				1.23
			],
			[
				350,
				0.520604,
				1.23
			],
			[
				400,
				0.526747,
				1.23
			],
			[
				450,
				0.528838,
				1.23
			],
			[
				500,
				0.530929,
				1.23
			],
			[
				550,
				0.533617,
				1.23
			],
			[
				600,
				0.536304,
				1.23
			],
			[
				650,
				0.539291,
				1.23
			],
			[
				700,
				0.542278,
				1.23
			],
			[
				750,
				0.545578,
				1.23
			],
			[
				800,
				0.548878,
				1.23
			],
			[
				850,
				0.553676,
				1.23
			],
			[
				900,
				0.558474,
				1.23
			],
			[
				950,
				0.568973,
				1.23
			]
		],
		"variants": [
			{
				"italic": [
					0,
					1
				],
				"weight": [
					100,
					950
				],
				"width": [
					50,
					150
				]
			}
		]
	},
	"Pomfret": {
		"features": [
			"calt",
			"case",
			"dlig",
			"kern",
			"liga",
			"mark",
			"onum",
			"ornm",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08"
		],
		"metrics": [
			[
				400,
				0.4306,
				1.2
			]
		],
		"variants": [
			{
			}
		]
	},
	"Protest Grotesk": {
		"axes": {
			"slnt": [
				"Slant",
				-11,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.508912,
				1.263158
			],
			[
				150,
				0.512353,
				1.263158
			],
			[
				200,
				0.515793,
				1.263158
			],
			[
				250,
				0.519233,
				1.263158
			],
			[
				300,
				0.522673,
				1.263158
			],
			[
				350,
				0.529554,
				1.263158
			],
			[
				400,
				0.536435,
				1.263158
			],
			[
				450,
				0.553945,
				1.263158
			],
			[
				500,
				0.571832,
				1.263158
			],
			[
				550,
				0.576176,
				1.263158
			],
			[
				600,
				0.58052,
				1.263158
			],
			[
				650,
				0.584863,
				1.263158
			],
			[
				700,
				0.589207,
				1.263158
			],
			[
				750,
				0.598153,
				1.263158
			],
			[
				800,
				0.607099,
				1.263158
			],
			[
				850,
				0.615851,
				1.263158
			],
			[
				900,
				0.624604,
				1.263158
			]
		],
		"variants": [
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Quasar": {
		"features": [
			"aalt",
			"calt",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"rvrn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"sups"
		],
		"isVariable": true,
		"metrics": [
			[
				10,
				0.519067,
				1.2
			],
			[
				50,
				0.519067,
				1.2
			],
			[
				100,
				0.519067,
				1.2
			],
			[
				150,
				0.519067,
				1.2
			],
			[
				180,
				0.519067,
				1.2
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					10,
					180
				]
			}
		]
	},
	"Resist Mono": {
		"featureGroups": [
			{
				"features": [
					"ss03"
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							100,
							900
						]
					}
				]
			},
			{
				"features": [
					"salt",
					"ss01",
					"ss02"
				],
				"variants": [
					{
						"weight": [
							100,
							900
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"c2sc",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"smcp",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				100,
				0.592,
				1.1
			],
			[
				150,
				0.592,
				1.1
			],
			[
				200,
				0.592,
				1.1
			],
			[
				250,
				0.592,
				1.1
			],
			[
				300,
				0.592,
				1.1
			],
			[
				350,
				0.592,
				1.1
			],
			[
				400,
				0.592,
				1.1
			],
			[
				450,
				0.592,
				1.1
			],
			[
				500,
				0.592,
				1.1
			],
			[
				550,
				0.592,
				1.1
			],
			[
				600,
				0.592,
				1.1
			],
			[
				650,
				0.592,
				1.1
			],
			[
				700,
				0.592,
				1.1
			],
			[
				750,
				0.592,
				1.1
			],
			[
				800,
				0.592,
				1.1
			],
			[
				850,
				0.592,
				1.1
			],
			[
				900,
				0.592,
				1.1
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					900
				]
			},
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Roslindale Extended": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss05",
			"ss12"
		],
		"isVariable": true,
		"metrics": [
			[
				400,
				0.548907,
				1.2
			]
		],
		"variants": [
			{
				"width": [
					80,
					150
				]
			}
		]
	},
	"SFT Schrifted Serif": {
		"axes": {
			"opsz": [
				"Optical size",
				12,
				36,
				36,
				0.01
			]
		},
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							200,
							900
						]
					}
				]
			},
			{
				"features": [
					"ss01"
				],
				"variants": [
					{
						"weight": [
							200,
							900
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss12",
			"ss13",
			"ss14",
			"ss15",
			"ss16",
			"ss17",
			"ss18",
			"ss19",
			"ss20",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"metrics": [
			[
				200,
				0.541733,
				1.19
			],
			[
				250,
				0.541733,
				1.19
			],
			[
				300,
				0.541733,
				1.19
			],
			[
				350,
				0.541733,
				1.19
			],
			[
				400,
				0.541733,
				1.19
			],
			[
				450,
				0.541733,
				1.19
			],
			[
				500,
				0.541733,
				1.19
			],
			[
				550,
				0.541733,
				1.19
			],
			[
				600,
				0.541733,
				1.19
			],
			[
				650,
				0.541733,
				1.19
			],
			[
				700,
				0.541733,
				1.19
			],
			[
				750,
				0.541733,
				1.19
			],
			[
				800,
				0.541733,
				1.19
			],
			[
				850,
				0.541733,
				1.19
			],
			[
				900,
				0.541733,
				1.19
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					200,
					900
				]
			},
			{
				"weight": [
					200,
					900
				]
			}
		]
	},
	"Salome": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"metrics": [
			[
				400,
				0.597614,
				1
			]
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Salome Deco": {
		"features": [
			"aalt",
			"dlig",
			"kern",
			"salt",
			"swsh"
		],
		"metrics": [
			[
				400,
				0.550107,
				1
			]
		],
		"variants": [
			{
			}
		]
	},
	"Salome Fine": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"metrics": [
			[
				400,
				0.597614,
				1
			]
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Salome Stencil": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"metrics": [
			[
				400,
				0.598672,
				1
			]
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Satoshi": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"pnum",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				300,
				0.492347,
				1.35
			],
			[
				350,
				0.49886,
				1.35
			],
			[
				400,
				0.505373,
				1.35
			],
			[
				450,
				0.512508,
				1.35
			],
			[
				500,
				0.519642,
				1.35
			],
			[
				550,
				0.523674,
				1.35
			],
			[
				600,
				0.527706,
				1.35
			],
			[
				650,
				0.531738,
				1.35
			],
			[
				700,
				0.53577,
				1.35
			],
			[
				750,
				0.540422,
				1.35
			],
			[
				800,
				0.545075,
				1.35
			],
			[
				850,
				0.549727,
				1.35
			],
			[
				900,
				0.55438,
				1.35
			]
		],
		"variants": [
			{
				"weight": [
					300,
					900
				]
			},
			{
				"italic": 1,
				"weight": [
					300,
					900
				]
			}
		]
	},
	"Sawton Bauhaus": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum",
			"zero"
		],
		"metrics": [
			[
				100,
				0.475773,
				1.2
			],
			[
				300,
				0.4761,
				1.2
			],
			[
				400,
				0.476433,
				1.2
			],
			[
				500,
				0.4805,
				1.2
			],
			[
				700,
				0.48614,
				1.2
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Sawton Circular": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum",
			"zero"
		],
		"metrics": [
			[
				100,
				0.476767,
				1.2
			],
			[
				300,
				0.47694,
				1.2
			],
			[
				400,
				0.4771,
				1.2
			],
			[
				500,
				0.481127,
				1.2
			],
			[
				700,
				0.486727,
				1.2
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Sawton Industrial": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum",
			"zero"
		],
		"metrics": [
			[
				100,
				0.47724,
				1.2
			],
			[
				300,
				0.47738,
				1.2
			],
			[
				400,
				0.47754,
				1.2
			],
			[
				500,
				0.481493,
				1.2
			],
			[
				700,
				0.48696,
				1.2
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Scilla": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"ornm",
			"salt",
			"ss01",
			"sups",
			"swsh"
		],
		"metrics": [
			[
				400,
				0.50922,
				1
			]
		],
		"variants": [
			{
			},
			{
				"italic": 1
			},
			{
				"width": 75
			},
			{
				"italic": 1,
				"width": 75
			}
		]
	},
	"Silka": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.559235,
				1
			],
			[
				200,
				0.557786,
				1
			],
			[
				300,
				0.55528,
				1
			],
			[
				400,
				0.553743,
				1
			],
			[
				500,
				0.555957,
				1
			],
			[
				600,
				0.558353,
				1
			],
			[
				700,
				0.560671,
				1
			],
			[
				900,
				0.563695,
				1
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Silka Mono": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"weight": 900
					},
					{
						"weight": 700
					},
					{
						"weight": 200
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					},
					{
						"weight": 100
					}
				]
			},
			{
				"features": [
					"liga"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 200
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"mark",
			"sups"
		],
		"metrics": [
			[
				100,
				0.679688,
				1
			],
			[
				200,
				0.679688,
				1
			],
			[
				300,
				0.679688,
				1
			],
			[
				400,
				0.679688,
				1
			],
			[
				500,
				0.679688,
				1
			],
			[
				600,
				0.679688,
				1
			],
			[
				700,
				0.679688,
				1
			],
			[
				900,
				0.679688,
				1
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Softcore": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"rlig",
			"sinf",
			"subs",
			"sups"
		],
		"isVariable": true,
		"metrics": [
			[
				400,
				0.541967,
				1.23
			]
		],
		"variants": [
			{
				"weight": [
					10,
					1000
				]
			},
			{
				"italic": 1,
				"weight": [
					10,
					1000
				]
			}
		]
	},
	"Strawford": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.513153,
				1
			],
			[
				200,
				0.513473,
				1
			],
			[
				300,
				0.51374,
				1
			],
			[
				400,
				0.51406,
				1
			],
			[
				500,
				0.51524,
				1
			],
			[
				700,
				0.516567,
				1
			],
			[
				900,
				0.51758,
				1
			]
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"SuperDuper": {
		"features": [
			"aalt",
			"salt",
			"ss01"
		],
		"metrics": [
			[
				300,
				0.242447,
				1.2
			],
			[
				400,
				0.256553,
				1.2
			],
			[
				500,
				0.2706,
				1.2
			],
			[
				700,
				0.284707,
				1.2
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			}
		]
	},
	"Ufficio Display": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss05",
			"ss07",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				300,
				0.49882,
				1.23
			],
			[
				350,
				0.49882,
				1.23
			],
			[
				400,
				0.49882,
				1.23
			],
			[
				450,
				0.49882,
				1.23
			],
			[
				500,
				0.49882,
				1.23
			],
			[
				550,
				0.49882,
				1.23
			],
			[
				600,
				0.49882,
				1.23
			],
			[
				650,
				0.49882,
				1.23
			],
			[
				700,
				0.49882,
				1.23
			],
			[
				750,
				0.49882,
				1.23
			],
			[
				800,
				0.49882,
				1.23
			],
			[
				850,
				0.49882,
				1.23
			],
			[
				900,
				0.49882,
				1.23
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					300,
					900
				]
			}
		]
	},
	"Ufficio Sans": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss07",
			"ss13",
			"ss18",
			"subs",
			"sups",
			"titl",
			"tnum"
		],
		"isVariable": true,
		"metrics": [
			[
				300,
				0.493753,
				1.23
			],
			[
				350,
				0.493753,
				1.23
			],
			[
				400,
				0.493753,
				1.23
			],
			[
				450,
				0.493753,
				1.23
			],
			[
				500,
				0.493753,
				1.23
			],
			[
				550,
				0.493753,
				1.23
			],
			[
				600,
				0.493753,
				1.23
			],
			[
				650,
				0.493753,
				1.23
			],
			[
				700,
				0.493753,
				1.23
			],
			[
				750,
				0.493753,
				1.23
			],
			[
				800,
				0.493753,
				1.23
			],
			[
				850,
				0.493753,
				1.23
			],
			[
				900,
				0.493753,
				1.23
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": [
					300,
					900
				]
			}
		]
	},
	"Victor Mono": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"subs",
			"sups"
		],
		"metrics": [
			[
				100,
				0.545455,
				1.409091
			],
			[
				200,
				0.545455,
				1.409091
			],
			[
				300,
				0.545455,
				1.409091
			],
			[
				400,
				0.545455,
				1.409091
			],
			[
				500,
				0.545455,
				1.409091
			],
			[
				600,
				0.545455,
				1.409091
			],
			[
				700,
				0.545455,
				1.409091
			]
		],
		"multiplexed": true,
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"oblique": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"oblique": 1,
				"weight": 200
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"oblique": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"oblique": 1,
				"weight": 500
			},
			{
				"oblique": 1
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"oblique": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"oblique": 1,
				"weight": 100
			}
		]
	},
	"Warbler Text": {
		"featureGroups": [
			{
				"features": [
					"dlig",
					"ss01",
					"ss02"
				],
				"variants": [
					{
						"italic": 1
					}
				]
			},
			{
				"features": [
					"c2sc",
					"dnom",
					"frac",
					"lnum",
					"numr",
					"onum",
					"sinf",
					"smcp",
					"subs",
					"sups"
				],
				"variants": [
					{
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn"
		],
		"metrics": [
			[
				400,
				0.533493,
				1.2
			]
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Wotfard": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"sups",
			"tnum"
		],
		"metrics": [
			[
				100,
				0.530153,
				1
			],
			[
				200,
				0.530589,
				1
			],
			[
				300,
				0.531032,
				1
			],
			[
				400,
				0.53154,
				1
			],
			[
				500,
				0.534811,
				1
			],
			[
				600,
				0.538115,
				1
			],
			[
				700,
				0.54141,
				1
			]
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	}
};
