// This file is generated by yarn scan-fonts. Do not edit.
export default {
	"ALT Riviera": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					200,
					800
				]
			}
		]
	},
	"AUTHENTIC Classified": {
		"features": [
		],
		"variants": [
			{
			}
		]
	},
	"AUTHENTIC Sans": {
		"features": [
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 900
			},
			{
				"weight": 300
			},
			{
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 900,
				"width": 75
			},
			{
				"weight": 300,
				"width": 75
			},
			{
				"width": 75
			}
		]
	},
	"Acorn": {
		"features": [
			"aalt",
			"calt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"ss01"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					100,
					700
				]
			}
		]
	},
	"Apfel Grotezk": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"frac",
			"kern",
			"mark",
			"ordn",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
			}
		]
	},
	"Apfel Grotezk Brukt": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"frac",
			"kern",
			"mark",
			"ordn",
			"sups"
		],
		"variants": [
			{
			}
		]
	},
	"Archia": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"weight": 100
			}
		]
	},
	"Argesta Display": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"variants": [
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Argesta Hairline": {
		"featureGroups": [
			{
				"features": [
					"dlig"
				],
				"variants": [
					{
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"variants": [
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Argesta Headline": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"variants": [
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Argesta Text": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
			},
			{
				"italic": 1
			}
		]
	},
	"Bagnard": {
		"features": [
			"cpsp",
			"kern",
			"liga"
		],
		"variants": [
			{
			}
		]
	},
	"Bariol": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"ornm",
			"pnum",
			"salt",
			"sinf",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"Bariol Serif": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"ornm",
			"pnum",
			"salt",
			"sinf",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"Basier Circle": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"kern",
			"mark",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Basier Circle Mono": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
					"kern"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"mark",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Basier Square": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"kern",
			"mark",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Basier Square Mono": {
		"featureGroups": [
			{
				"features": [
					"ordn",
					"salt",
					"ss01"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
					"kern"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"mark",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Blackout 2AM": {
		"features": [
			"kern"
		],
		"variants": [
			{
			}
		]
	},
	"Blackout Midnight": {
		"features": [
			"kern"
		],
		"variants": [
			{
			}
		]
	},
	"Blackout Sunrise": {
		"features": [
			"kern"
		],
		"variants": [
			{
			}
		]
	},
	"Bloyd": {
		"axes": {
			"slnt": [
				"Slant",
				-10,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12",
			"ss13",
			"ss14",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					200,
					900
				]
			}
		]
	},
	"Bould": {
		"features": [
			"aalt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Bureau Serif": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss10",
			"ss11",
			"subs",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Butler": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"lnum",
			"onum",
			"ordn",
			"pnum",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"weight": 200
			},
			{
			}
		]
	},
	"Butler Stencil": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"lnum",
			"onum",
			"ordn",
			"pnum",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"weight": 200
			},
			{
			}
		]
	},
	"Cabrio": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							300,
							950
						]
					}
				]
			},
			{
				"features": [
					"ss02"
				],
				"variants": [
					{
						"weight": [
							300,
							950
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					300,
					950
				]
			},
			{
				"weight": [
					300,
					950
				]
			}
		]
	},
	"Calendas Plus": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"ornm",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Cartograph CF": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 800
					},
					{
						"italic": 1,
						"weight": 200
					},
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			},
			{
				"features": [
					"ss03"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 600
					},
					{
						"weight": 800
					},
					{
						"weight": 200
					},
					{
						"weight": 900
					},
					{
						"weight": 300
					},
					{
					},
					{
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss05",
			"sups",
			"vert",
			"vrt2"
		],
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"Cassannet Plus": {
		"features": [
			"aalt",
			"dlig",
			"kern",
			"ornm",
			"salt",
			"sups"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
			},
			{
				"weight": 100
			},
			{
				"weight": 950
			}
		]
	},
	"Chaney": {
		"features": [
			"aalt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"sups"
		],
		"variants": [
			{
				"width": 125
			},
			{
			},
			{
				"width": 200
			},
			{
				"width": 112.5
			}
		]
	},
	"Cloitre": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05"
		],
		"variants": [
			{
			}
		]
	},
	"Cloitre Rounded": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05"
		],
		"variants": [
			{
			}
		]
	},
	"Cooper Hewitt": {
		"features": [
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"numr",
			"sinf",
			"ss01",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
			}
		]
	},
	"Crit": {
		"features": [
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"subs",
			"sups"
		],
		"variants": [
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"italic": 1
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 600
			}
		]
	},
	"DaVinci": {
		"featureGroups": [
			{
				"features": [
					"ccmp",
					"mark",
					"mkmk"
				],
				"variants": [
					{
						"weight": 700
					},
					{
						"weight": 900
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					},
					{
						"weight": 100
					}
				]
			},
			{
				"features": [
					"dnom",
					"frac",
					"numr",
					"sinf",
					"ss01",
					"ss02",
					"ss03",
					"subs",
					"sups"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"dlig",
			"kern",
			"liga",
			"lnum",
			"onum",
			"pnum",
			"tnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Def Sans": {
		"axes": {
			"slnt": [
				"Slant",
				-8,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					100,
					900
				],
				"width": [
					75,
					100
				]
			}
		]
	},
	"Easy Grotesk": {
		"axes": {
			"slnt": [
				"Slant",
				0,
				10,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"fwid",
			"kern",
			"liga",
			"lnum",
			"locl",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss10",
			"ss11",
			"ss12",
			"ss13",
			"ss14",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					200,
					900
				]
			}
		]
	},
	"Ernst": {
		"features": [
			"aalt",
			"c2sc",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"salt",
			"sinf",
			"smcp",
			"ss01",
			"ss02",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					800
				]
			},
			{
				"weight": [
					100,
					800
				]
			}
		]
	},
	"FL Prefere": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"kern",
			"liga",
			"mark"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					300,
					800
				]
			},
			{
				"italic": 1,
				"weight": [
					300,
					800
				]
			}
		]
	},
	"Gangster Grotesk": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"ss01",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
			}
		]
	},
	"Geomanist": {
		"features": [
			"aalt",
			"case",
			"frac",
			"kern",
			"liga",
			"ordn",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 450
			},
			{
				"weight": 450
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
				"italic": 1
			},
			{
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"weight": 950
			}
		]
	},
	"Gestura Text": {
		"featureGroups": [
			{
				"features": [
					"mkmk",
					"ss04",
					"ss05",
					"ss06"
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							100,
							900
						]
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"weight": [
							100,
							900
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"subs",
			"sups",
			"titl",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					900
				]
			},
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Golos UI": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"cpsp",
			"frac",
			"kern",
			"ordn",
			"sups"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					400,
					700
				]
			}
		]
	},
	"Gosh": {
		"features": [
			"aalt",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"pnum",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 900,
				"width": 75
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 800,
				"width": 75
			},
			{
				"weight": 800
			},
			{
				"weight": 900,
				"width": 62.5
			},
			{
				"weight": 700,
				"width": 62.5
			},
			{
				"weight": 800,
				"width": 62.5
			},
			{
				"weight": 900,
				"width": 150
			},
			{
				"weight": 700,
				"width": 150
			},
			{
				"weight": 800,
				"width": 150
			},
			{
				"weight": 900,
				"width": 87.5
			},
			{
				"weight": 700,
				"width": 87.5
			},
			{
				"weight": 800,
				"width": 87.5
			},
			{
				"weight": 900,
				"width": 125
			},
			{
				"weight": 700,
				"width": 125
			},
			{
				"weight": 800,
				"width": 125
			}
		]
	},
	"Greycliff CF": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"ss01",
			"ss02",
			"ss03",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"oblique": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"oblique": 1,
				"weight": 600
			},
			{
				"weight": 600
			},
			{
				"oblique": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"oblique": 1,
				"weight": 200
			},
			{
				"weight": 200
			},
			{
				"oblique": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"oblique": 1,
				"weight": 300
			},
			{
				"weight": 300
			},
			{
				"oblique": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
				"oblique": 1
			},
			{
			},
			{
				"oblique": 1,
				"weight": 100
			},
			{
				"weight": 100
			}
		]
	},
	"HEX Franklin": {
		"features": [
			"calt",
			"case",
			"kern",
			"mark",
			"pnum",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss07",
			"ss08",
			"ss15",
			"ss16",
			"ss17",
			"titl",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					1,
					1000
				],
				"width": [
					60,
					120
				]
			}
		]
	},
	"HEX Franklin Tyght": {
		"axes": {
			"NOTC": [
				"Not Touching",
				0,
				1,
				0,
				0.01
			],
			"TYTE": [
				"Tyght",
				-100,
				0,
				-100,
				0.01
			]
		},
		"features": [
			"kern",
			"mark",
			"ss04",
			"ss05",
			"ss08",
			"ss15",
			"titl"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": 800,
				"width": [
					60,
					100
				]
			}
		]
	},
	"Henrietta": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"clig",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 900,
				"width": 75
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 300,
				"width": 75
			},
			{
				"weight": 500,
				"width": 75
			},
			{
				"width": 75
			},
			{
				"weight": 600,
				"width": 75
			}
		]
	},
	"Hop": {
		"axes": {
			"cstm": [
				"Rounded",
				0,
				100,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Hypertext Display": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Integral CF": {
		"features": [
			"aalt",
			"cpsp",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01"
		],
		"variants": [
			{
				"oblique": 1,
				"weight": 700
			},
			{
				"weight": 700
			},
			{
				"oblique": 1,
				"weight": 600
			},
			{
				"weight": 600
			},
			{
				"oblique": 1,
				"weight": 800
			},
			{
				"weight": 800
			},
			{
				"oblique": 1,
				"weight": 900
			},
			{
				"weight": 900
			},
			{
				"oblique": 1,
				"weight": 500
			},
			{
				"weight": 500
			},
			{
				"oblique": 1
			},
			{
			}
		]
	},
	"Job Clarendon": {
		"features": [
			"aalt",
			"calt",
			"case",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"zero"
		],
		"variants": [
			{
				"weight": 1,
				"width": 62.5
			},
			{
				"weight": 1,
				"width": 75
			},
			{
				"weight": 1,
				"width": 50
			}
		]
	},
	"Junction": {
		"features": [
			"aalt",
			"kern",
			"liga",
			"lnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
			}
		]
	},
	"Knile": {
		"features": [
			"aalt",
			"calt",
			"cpsp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"League Mono": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"mark",
			"mkmk",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"tnum"
		],
		"variants": [
			{
				"weight": 700,
				"width": 112.5
			},
			{
				"weight": 700,
				"width": 50
			},
			{
				"weight": 800,
				"width": 50
			},
			{
				"weight": 300,
				"width": 50
			},
			{
				"weight": 500,
				"width": 50
			},
			{
				"width": 50
			},
			{
				"weight": 600,
				"width": 50
			},
			{
				"weight": 100,
				"width": 50
			},
			{
				"weight": 200,
				"width": 50
			},
			{
				"weight": 700,
				"width": 200
			},
			{
				"weight": 800,
				"width": 200
			},
			{
				"weight": 300,
				"width": 200
			},
			{
				"weight": 500,
				"width": 200
			},
			{
				"width": 200
			},
			{
				"weight": 600,
				"width": 200
			},
			{
				"weight": 100,
				"width": 200
			},
			{
				"weight": 200,
				"width": 200
			},
			{
				"weight": 800,
				"width": 112.5
			},
			{
				"weight": 300,
				"width": 112.5
			},
			{
				"weight": 500,
				"width": 112.5
			},
			{
				"weight": 700,
				"width": 75
			},
			{
				"weight": 800,
				"width": 75
			},
			{
				"weight": 300,
				"width": 75
			},
			{
				"weight": 500,
				"width": 75
			},
			{
				"width": 75
			},
			{
				"weight": 600,
				"width": 75
			},
			{
				"weight": 100,
				"width": 75
			},
			{
				"weight": 200,
				"width": 75
			},
			{
				"width": 112.5
			},
			{
				"weight": 600,
				"width": 112.5
			},
			{
				"weight": 100,
				"width": 112.5
			},
			{
				"weight": 200,
				"width": 112.5
			},
			{
				"weight": 700,
				"width": 150
			},
			{
				"weight": 800,
				"width": 150
			},
			{
				"weight": 300,
				"width": 150
			},
			{
				"weight": 500,
				"width": 150
			},
			{
				"width": 150
			},
			{
				"weight": 600,
				"width": 150
			},
			{
				"weight": 100,
				"width": 150
			},
			{
				"weight": 200,
				"width": 150
			}
		]
	},
	"Liberation Mono": {
		"features": [
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Liberation Sans": {
		"features": [
			"ccmp",
			"kern"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Liberation Serif": {
		"features": [
			"ccmp",
			"kern"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Loretta": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"sinf",
			"subs",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Louche": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"numr",
			"onum",
			"ordn",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"subs",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			}
		]
	},
	"MD Nichrome": {
		"axes": {
			"slnt": [
				"Slant",
				-10,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cv01",
			"cv02",
			"cv03",
			"cv04",
			"cv05",
			"cv06",
			"cv07",
			"cv08",
			"cv09",
			"cv10",
			"cv11",
			"cv12",
			"cv13",
			"cv14",
			"cv15",
			"cv16",
			"cv17",
			"cv18",
			"cv19",
			"cv20",
			"cv21",
			"cv22",
			"cv23",
			"cv24",
			"cv25",
			"cv26",
			"cv27",
			"dnom",
			"frac",
			"kern",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"MUSETTA": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01",
			"sups"
		],
		"variants": [
			{
			}
		]
	},
	"Macabre": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"kern",
			"liga",
			"mark",
			"mkmk"
		],
		"variants": [
			{
			}
		]
	},
	"Marcin Antique": {
		"featureGroups": [
			{
				"features": [
					"ss08"
				],
				"variants": [
					{
						"weight": 900
					},
					{
						"weight": 700
					},
					{
						"weight": 450
					},
					{
						"weight": 800
					},
					{
						"weight": 200
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					},
					{
						"weight": 950
					},
					{
						"weight": 100
					}
				]
			},
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 450
					},
					{
						"italic": 1,
						"weight": 800
					},
					{
						"italic": 1,
						"weight": 200
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 950
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss07",
			"subs",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 450
			},
			{
				"italic": 1,
				"weight": 450
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 950
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"McQueen": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 1000
			},
			{
				"italic": 1,
				"weight": 1000
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			}
		]
	},
	"Megazoid": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"variants": [
			{
			}
		]
	},
	"Megazoid Fill": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"variants": [
			{
			}
		]
	},
	"Megazoid Shade Left": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"variants": [
			{
			}
		]
	},
	"Megazoid Shade Right": {
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12"
		],
		"variants": [
			{
			}
		]
	},
	"Metra": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"subs",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 950
			}
		]
	},
	"Metropolis": {
		"features": [
			"kern",
			"mark",
			"mkmk"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Micrograph": {
		"features": [
			"aalt",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"rlig",
			"sinf",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					800
				]
			},
			{
				"weight": [
					100,
					800
				]
			}
		]
	},
	"Mint Grotesk": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 950
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Mint Grotesk Display": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"weight": 950
			},
			{
				"italic": 1,
				"weight": 950
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Nicephore": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dlig",
			"dnom",
			"frac",
			"hist",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"rlig",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"ss10",
			"ss11",
			"ss12",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					0,
					1000
				]
			}
		]
	},
	"Nickel": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02"
		],
		"variants": [
			{
			}
		]
	},
	"Nickel Gothic": {
		"axes": {
			"slnt": [
				"Slant",
				-15,
				15,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06"
		],
		"isVariable": true,
		"variants": [
			{
			},
			{
				"width": 125
			},
			{
				"width": 150
			},
			{
				"width": [
					100,
					150
				]
			}
		]
	},
	"Nickel Open Face": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"ss01",
			"ss02"
		],
		"variants": [
			{
			}
		]
	},
	"Noway": {
		"features": [
			"aalt",
			"dlig",
			"frac",
			"kern",
			"liga",
			"ordn",
			"sups",
			"tnum",
			"zero"
		],
		"variants": [
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"italic": 1
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Noway Round": {
		"features": [
			"kern"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Open Sauce One": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"weight": 900
					},
					{
						"weight": 700
					},
					{
						"weight": 800
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					}
				]
			},
			{
				"features": [
					"pnum",
					"tnum"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 800
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1,
						"weight": 600
					}
				]
			}
		],
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Open Sauce Sans": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"pnum",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Open Sauce Two": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn",
			"pnum",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 800
			},
			{
				"italic": 1,
				"weight": 800
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			}
		]
	},
	"Output Sans 2 Beta": {
		"axes": {
			"GRAD": [
				"Grade",
				0,
				10,
				0,
				0.01
			],
			"TERM": [
				"Terminals",
				-1,
				1,
				0,
				0.01
			],
			"opsz": [
				"Optical size",
				10,
				48,
				48,
				0.01
			],
			"slnt": [
				"Slant",
				-13,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"ccmp",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"rlig",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					1,
					800
				],
				"width": [
					75,
					125
				]
			}
		]
	},
	"PARKING": {
		"features": [
			"aalt",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"sups"
		],
		"variants": [
			{
			}
		]
	},
	"PT Root UI": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"cpsp",
			"dlig",
			"dnom",
			"frac",
			"hist",
			"kern",
			"liga",
			"numr",
			"ordn",
			"pnum",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					300,
					700
				]
			}
		]
	},
	"Peridot PE": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"cpsp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"rvrn",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"ss09",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"italic": [
					0,
					1
				],
				"weight": [
					100,
					950
				],
				"width": [
					50,
					150
				]
			}
		]
	},
	"Pomfret": {
		"features": [
			"calt",
			"case",
			"dlig",
			"kern",
			"liga",
			"mark",
			"onum",
			"ornm",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08"
		],
		"variants": [
			{
			}
		]
	},
	"Protest Grotesk": {
		"axes": {
			"slnt": [
				"Slant",
				-11,
				0,
				0,
				0.01
			]
		},
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Quasar": {
		"features": [
			"aalt",
			"calt",
			"ccmp",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"rvrn",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"sups"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					10,
					180
				]
			}
		]
	},
	"Resist Mono": {
		"featureGroups": [
			{
				"features": [
					"ss03"
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							100,
							900
						]
					}
				]
			},
			{
				"features": [
					"salt",
					"ss01",
					"ss02"
				],
				"variants": [
					{
						"weight": [
							100,
							900
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"c2sc",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"smcp",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					100,
					900
				]
			},
			{
				"weight": [
					100,
					900
				]
			}
		]
	},
	"Roslindale Extended": {
		"features": [
			"aalt",
			"ccmp",
			"dlig",
			"kern",
			"mark",
			"mkmk",
			"ordn",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"ss05",
			"ss12"
		],
		"isVariable": true,
		"variants": [
			{
				"width": [
					80,
					150
				]
			}
		]
	},
	"SFT Schrifted Serif": {
		"axes": {
			"opsz": [
				"Optical size",
				12,
				36,
				36,
				0.01
			]
		},
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"italic": 1,
						"weight": [
							200,
							900
						]
					}
				]
			},
			{
				"features": [
					"ss01"
				],
				"variants": [
					{
						"weight": [
							200,
							900
						]
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"pnum",
			"sinf",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss12",
			"ss13",
			"ss14",
			"ss15",
			"ss16",
			"ss17",
			"ss18",
			"ss19",
			"ss20",
			"subs",
			"sups",
			"tnum",
			"zero"
		],
		"isVariable": true,
		"variants": [
			{
				"italic": 1,
				"weight": [
					200,
					900
				]
			},
			{
				"weight": [
					200,
					900
				]
			}
		]
	},
	"Salome": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Salome Deco": {
		"features": [
			"aalt",
			"dlig",
			"kern",
			"salt",
			"swsh"
		],
		"variants": [
			{
			}
		]
	},
	"Salome Fine": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Salome Stencil": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"numr",
			"onum",
			"ordn",
			"salt",
			"sinf",
			"smcp",
			"sups",
			"swsh"
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Satoshi": {
		"features": [
			"aalt",
			"case",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"numr",
			"ordn",
			"pnum",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					300,
					900
				]
			},
			{
				"italic": 1,
				"weight": [
					300,
					900
				]
			}
		]
	},
	"Sawton Bauhaus": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum",
			"zero"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Sawton Circular": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum",
			"zero"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Sawton Industrial": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum",
			"zero"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			},
			{
				"weight": 100
			}
		]
	},
	"Scilla": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"ornm",
			"salt",
			"ss01",
			"sups",
			"swsh"
		],
		"variants": [
			{
			},
			{
				"italic": 1
			},
			{
				"width": 75
			},
			{
				"italic": 1,
				"width": 75
			}
		]
	},
	"Silka": {
		"features": [
			"aalt",
			"frac",
			"kern",
			"liga",
			"mark",
			"pnum",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Silka Mono": {
		"featureGroups": [
			{
				"features": [
				],
				"variants": [
					{
						"weight": 900
					},
					{
						"weight": 700
					},
					{
						"weight": 200
					},
					{
						"weight": 300
					},
					{
						"weight": 500
					},
					{
					},
					{
						"weight": 600
					},
					{
						"weight": 100
					}
				]
			},
			{
				"features": [
					"liga"
				],
				"variants": [
					{
						"italic": 1,
						"weight": 900
					},
					{
						"italic": 1,
						"weight": 700
					},
					{
						"italic": 1,
						"weight": 200
					},
					{
						"italic": 1,
						"weight": 300
					},
					{
						"italic": 1,
						"weight": 500
					},
					{
						"italic": 1
					},
					{
						"italic": 1,
						"weight": 600
					},
					{
						"italic": 1,
						"weight": 100
					}
				]
			}
		],
		"features": [
			"aalt",
			"frac",
			"mark",
			"sups"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"Softcore": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"lnum",
			"mark",
			"mkmk",
			"numr",
			"onum",
			"ordn",
			"rlig",
			"sinf",
			"subs",
			"sups"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					10,
					1000
				]
			},
			{
				"italic": 1,
				"weight": [
					10,
					1000
				]
			}
		]
	},
	"Strawford": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"mark",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 900
			},
			{
				"italic": 1,
				"weight": 900
			},
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	},
	"SuperDuper": {
		"features": [
			"aalt",
			"salt",
			"ss01"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"weight": 300
			},
			{
				"weight": 500
			},
			{
			}
		]
	},
	"Ufficio Display": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss05",
			"ss07",
			"subs",
			"sups",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					300,
					900
				]
			}
		]
	},
	"Ufficio Sans": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"dlig",
			"dnom",
			"frac",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"pnum",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss07",
			"ss13",
			"ss18",
			"subs",
			"sups",
			"titl",
			"tnum"
		],
		"isVariable": true,
		"variants": [
			{
				"weight": [
					300,
					900
				]
			}
		]
	},
	"Victor Mono": {
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"dnom",
			"frac",
			"mark",
			"mkmk",
			"numr",
			"ordn",
			"salt",
			"sinf",
			"ss01",
			"ss02",
			"ss03",
			"ss04",
			"ss05",
			"ss06",
			"ss07",
			"ss08",
			"subs",
			"sups"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"oblique": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"oblique": 1,
				"weight": 200
			},
			{
				"italic": 1
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"oblique": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
				"oblique": 1,
				"weight": 500
			},
			{
				"oblique": 1
			},
			{
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"oblique": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			},
			{
				"oblique": 1,
				"weight": 100
			}
		]
	},
	"Warbler Text": {
		"featureGroups": [
			{
				"features": [
					"dlig",
					"ss01",
					"ss02"
				],
				"variants": [
					{
						"italic": 1
					}
				]
			},
			{
				"features": [
					"c2sc",
					"dnom",
					"frac",
					"lnum",
					"numr",
					"onum",
					"sinf",
					"smcp",
					"subs",
					"sups"
				],
				"variants": [
					{
					}
				]
			}
		],
		"features": [
			"aalt",
			"calt",
			"case",
			"ccmp",
			"kern",
			"liga",
			"mark",
			"mkmk",
			"ordn"
		],
		"variants": [
			{
				"italic": 1
			},
			{
			}
		]
	},
	"Wotfard": {
		"features": [
			"aalt",
			"case",
			"ccmp",
			"frac",
			"kern",
			"lnum",
			"mark",
			"onum",
			"ordn",
			"pnum",
			"salt",
			"ss01",
			"ss02",
			"ss03",
			"sups",
			"tnum"
		],
		"variants": [
			{
				"weight": 700
			},
			{
				"italic": 1,
				"weight": 700
			},
			{
				"weight": 200
			},
			{
				"italic": 1,
				"weight": 200
			},
			{
				"weight": 300
			},
			{
				"italic": 1,
				"weight": 300
			},
			{
				"weight": 500
			},
			{
				"italic": 1,
				"weight": 500
			},
			{
			},
			{
				"italic": 1
			},
			{
				"weight": 600
			},
			{
				"italic": 1,
				"weight": 600
			},
			{
				"weight": 100
			},
			{
				"italic": 1,
				"weight": 100
			}
		]
	}
};
