export default [
	"Amiko",
	"Anonymous Pro",
	"Asap",
	"Atkinson Hyperlegible Mono",
	"Azeret Mono",
	"B612 Mono",
	"Baloo 2",
	"Baloo Bhai 2",
	"Baloo Bhaijaan 2",
	"Baloo Bhaina 2",
	"Baloo Chettan 2",
	"Baloo Da 2",
	"Baloo Paaji 2",
	"Baloo Tamma 2",
	"Baloo Tammudu 2",
	"Baloo Thambi 2",
	"BIZ UDGothic",
	"BIZ UDMincho",
	"Brygada 1918",
	"Cabin Sketch",
	"Cartograph CF",
	"Cascadia Code",
	"Cascadia Mono",
	"Chivo Mono",
	"Codystar",
	"Courier New",
	"Courier Prime",
	"Cousine",
	"DM Mono",
	"Fira Code",
	"Fira Mono",
	"Geist Mono",
	"Golos UI",
	"IBM Plex Mono",
	"Inconsolata",
	"Jaldi",
	"JetBrains Mono",
	"Kaisei Decol",
	"Kaisei HarunoUmi",
	"Kaisei Opti",
	"Kode Mono",
	"League Mono",
	"Lekton",
	"Liberation Mono",
	"LXGW WenKai Mono TC",
	"M PLUS Code Latin",
	"M PLUS Rounded 1c",
	"Martian Mono",
	"Nanum Gothic",
	"Nanum Gothic Coding",
	"Nanum Myeongjo",
	"Noto Sans Mono",
	"Overpass Mono",
	"PT Root UI",
	"Red Hat Mono",
	"Redacted Script",
	"Reddit Mono",
	"Roboto Mono",
	"Silka Mono",
	"Sometype Mono",
	"Sono",
	"Source Code Pro",
	"Source Sans 3",
	"Source Serif 4",
	"Space Mono",
	"Spline Sans Mono",
	"Tourney",
	"Ubuntu Mono",
	"Ubuntu Sans Mono",
	"Victor Mono"
];
